import Head from 'next/head';
import { useState } from "react";
import styles from "../styles/Header.module.css"

const Header = () => {
  const [isOpen, setIsOpen]= useState(false);
  const openMenu = () => setIsOpen(!isOpen)

    return (
        <>
            <Head>
            <title>WeCould!</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="relative inset-x-0 top-0 z-10 h-20 min-w-full">
            {/* <div className="fixed inset-x-0 top-0 z-10 h-20 min-w-full text-white border-b border-purple-900 bg-transparent backdrop-filter backdrop-blur-lg bg-opacity-30"> */}
                <header className={styles.header}>
                    <nav className={styles.navbar}>
                        <ul className={styles.navlogo}>
                            <li>
                            <a href="https://twitter.com/_YouCould_" rel="noreferrer" target="_blank" >
                                <img src='https://static.wixstatic.com/media/01ab6619093f45388d66736ec22e5885.png/v1/fill/w_49,h_49,al_c,usm_0.66_1.00_0.01,enc_auto/01ab6619093f45388d66736ec22e5885.png'/>
                            </a>
                            </li>
                            <li>
                            <a href="https://www.instagram.com/youcould.info/" rel="noreferrer" target="_blank" >
                                <img src='https://static.wixstatic.com/media/81af6121f84c41a5b4391d7d37fce12a.png/v1/fill/w_49,h_49,al_c,usm_0.66_1.00_0.01,enc_auto/81af6121f84c41a5b4391d7d37fce12a.png'/>
                            </a>
                            </li>
                            <li>
                            <a href="https://www.youcould.info/" rel="noreferrer" target="_blank" >
                                <img src='https://static.wixstatic.com/media/2177b9_ab07ee4e85b7417ca4ecd3785648c500~mv2.png/v1/fill/w_49,h_49,al_c,usm_0.66_1.00_0.01,enc_auto/2177b9_ab07ee4e85b7417ca4ecd3785648c500~mv2.png'/>
                            </a>
                            </li>
                        </ul>
                        <ul className={isOpen === false ?
                        styles.navmenu : styles.navmenu +' '+ styles.active}> 
                        <li className={styles.navitem}>
                            <a href="https://www.youcould.info/" rel="noreferrer" target="_blank" className={styles.navlink}>YouCould</a>
                        </li>
                        <li className={styles.navitem}>
                            <a href="https://www.youcould.info/roadmap" rel="noreferrer" target="_blank" className={styles.navlink}>Roadmap</a>
                        </li>
                        <li className={styles.navitem}>
                            <a href="https://www.youcould.info/team-contact" className={styles.navlink}>Team </a>
                        </li>
                        </ul>
                        <button className={styles.SoonButton}>
                            <a>Soon</a> 
                        </button>

                        <button className={isOpen === false ? 
                        styles.hamburger : styles.hamburger +' '+ styles.active}
                        onClick={openMenu}>
                        <span className={styles.bar}></span>
                        <span className={styles.bar}></span>
                        <span className={styles.bar}></span>
                        
                        </button>
                    </nav>
                </header>
            </div>
        </>
    );
}
export default Header;
